### ISSUE TITLE
How do I localize standard menu items *from within* my startup module?

### ISSUE THREAD

**Issue by darestov** [tgjones/gemini#124]

**Comment by tgjones** [comment]
As you might have seen, the menu and toolbar subsystems have changed significantly since the last NuGet release - are you talking about the NuGet version, or the latest version here on GitHub?

**Comment by mwpowellhtx** [comment]
Thanks for responding. I have not seen lately, but I shall check it out. Thank you.

**Comment by darestov** [comment]
I am talking about latest version on GitHub. Among the commits, I found one where menu headers used to have theirs values from resources. But it seems that this commit was somehow discarded and resource values are not used thereafter. Tim, could you please comment on this and clarify the situation?

**Comment by tgjones** [comment]
@darestov I plan to go back to using resources for the menu item names, instead of hard-coding the strings - I just haven't done it while I'm still finalising the API.

I'll leave this issue open to remind me to do it before releasing v0.6.

**Comment by mwpowellhtx** [comment]
Would you mind clarifying? You are talking about resources in the WPF MVVM sense? i.e. Merged resources, etc, at the app, view, levels, etc? Thank you...

**Comment by tgjones** [comment]
@mwpowellhtx No, not WPF resources. @darestov was talking about localised menu item text, which was previously done (partially, for a few menu items) in Gemini using .NET's built-in support for resources and localisation.

**Comment by mwpowellhtx** [comment]
I need to clarify what I am expecting from this issue. Globalization/localization/translations, is a wholely separate matter from context-sensitive menus, tool buttons, command/action pattern. I want the ability to insert/remove/show/hide, etc, menus and such based on their commands (?), depending on which document(s) (?) are selected. Perhaps that already exists, I don't know?

**Comment by tgjones** [comment]
@mwpowellhtx that's a totally separate issue, nothing to do with this one. You and I have already discussed this before, in #90, and I said I plan to implement that kind of functionality in a similar way to Visual Studio, using command contexts. But let's not clutter up this issue further - this one is specifically related to localisation.

**Comment by mwpowellhtx** [comment]
Thanks for clarifying.
