### ISSUE TITLE
Samples not building

### ISSUE THREAD

**Issue by HellGate94** [tgjones/gemini#126]
First: The GraphDesigner demo link is incorrect in the documentation.

Main Issue: When building the samples there are a lot of buid errors:

    Error	1	The type 'SharpDX.Toolkit.Graphics.GraphicsDevice' is defined in an assembly that is not referenced. You must add a reference to assembly 'SharpDX.Toolkit.Graphics, Version=2.5.0.0, Culture=neutral, PublicKeyToken=null'.	D:\Users\xxx\Desktop\gemini-master\src\Gemini.Demo\Modules\SharpDXSceneViewer\Views\SceneView.xaml.cs	36	10	Gemini.Demo
    Error	2	The best overloaded method match for 'SharpDX.Toolkit.Graphics.BasicEffect.BasicEffect(SharpDX.Toolkit.Graphics.GraphicsDevice)' has some invalid arguments	D:\Users\xxx\Desktop\gemini-master\src\Gemini.Demo\Modules\SharpDXSceneViewer\Views\SceneView.xaml.cs	36	25	Gemini.Demo
    Error	3	Argument 1: cannot convert from 'SharpDX.Toolkit.Graphics.GraphicsDevice' to 'SharpDX.Toolkit.Graphics.GraphicsDevice [d:\Users\xxx\Desktop\gemini-master\src\packages\SharpDX.2.6.3\Bin\DirectX11-Signed-net40\SharpDX.Toolkit.Graphics.dll]'	D:\Users\xxx\Desktop\gemini-master\src\Gemini.Demo\Modules\SharpDXSceneViewer\Views\SceneView.xaml.cs	36	41	Gemini.Demo
    Error	4	The best overloaded method match for 'SharpDX.Toolkit.Graphics.GeometricPrimitive.Cube.New(SharpDX.Toolkit.Graphics.GraphicsDevice, float, bool)' has some invalid arguments	D:\Users\xxx\Desktop\gemini-master\src\Gemini.Demo\Modules\SharpDXSceneViewer\Views\SceneView.xaml.cs	46	17	Gemini.Demo
    Error	5	Argument 1: cannot convert from 'SharpDX.Toolkit.Graphics.GraphicsDevice' to 'SharpDX.Toolkit.Graphics.GraphicsDevice [d:\Users\xxx\Desktop\gemini-master\src\packages\SharpDX.2.6.3\Bin\DirectX11-Signed-net40\SharpDX.Toolkit.Graphics.dll]'	D:\Users\xxx\Desktop\gemini-master\src\Gemini.Demo\Modules\SharpDXSceneViewer\Views\SceneView.xaml.cs	46	45	Gemini.Demo
    Error	6	The best overloaded method match for 'SharpDX.Toolkit.Graphics.GeometricPrimitive.Cylinder.New(SharpDX.Toolkit.Graphics.GraphicsDevice, float, float, int, bool)' has some invalid arguments	D:\Users\xxx\Desktop\gemini-master\src\Gemini.Demo\Modules\SharpDXSceneViewer\Views\SceneView.xaml.cs	47	17	Gemini.Demo
    Error	7	Argument 1: cannot convert from 'SharpDX.Toolkit.Graphics.GraphicsDevice' to 'SharpDX.Toolkit.Graphics.GraphicsDevice [d:\Users\xxx\Desktop\gemini-master\src\packages\SharpDX.2.6.3\Bin\DirectX11-Signed-net40\SharpDX.Toolkit.Graphics.dll]'	D:\Users\xxx\Desktop\gemini-master\src\Gemini.Demo\Modules\SharpDXSceneViewer\Views\SceneView.xaml.cs	47	49	Gemini.Demo
    Error	8	The best overloaded method match for 'SharpDX.Toolkit.Graphics.GeometricPrimitive.GeoSphere.New(SharpDX.Toolkit.Graphics.GraphicsDevice, float, int, bool)' has some invalid arguments	D:\Users\xxx\Desktop\gemini-master\src\Gemini.Demo\Modules\SharpDXSceneViewer\Views\SceneView.xaml.cs	48	17	Gemini.Demo
    Error	9	Argument 1: cannot convert from 'SharpDX.Toolkit.Graphics.GraphicsDevice' to 'SharpDX.Toolkit.Graphics.GraphicsDevice [d:\Users\xxx\Desktop\gemini-master\src\packages\SharpDX.2.6.3\Bin\DirectX11-Signed-net40\SharpDX.Toolkit.Graphics.dll]'	D:\Users\xxx\Desktop\gemini-master\src\Gemini.Demo\Modules\SharpDXSceneViewer\Views\SceneView.xaml.cs	48	50	Gemini.Demo
    Error	10	The best overloaded method match for 'SharpDX.Toolkit.Graphics.GeometricPrimitive.Teapot.New(SharpDX.Toolkit.Graphics.GraphicsDevice, float, int, bool)' has some invalid arguments	D:\Users\xxx\Desktop\gemini-master\src\Gemini.Demo\Modules\SharpDXSceneViewer\Views\SceneView.xaml.cs	49	17	Gemini.Demo
    Error	11	Argument 1: cannot convert from 'SharpDX.Toolkit.Graphics.GraphicsDevice' to 'SharpDX.Toolkit.Graphics.GraphicsDevice [d:\Users\xxx\Desktop\gemini-master\src\packages\SharpDX.2.6.3\Bin\DirectX11-Signed-net40\SharpDX.Toolkit.Graphics.dll]'	D:\Users\xxx\Desktop\gemini-master\src\Gemini.Demo\Modules\SharpDXSceneViewer\Views\SceneView.xaml.cs	49	47	Gemini.Demo
    Error	12	The best overloaded method match for 'SharpDX.Toolkit.Graphics.GeometricPrimitive.Torus.New(SharpDX.Toolkit.Graphics.GraphicsDevice, float, float, int, bool)' has some invalid arguments	D:\Users\xxx\Desktop\gemini-master\src\Gemini.Demo\Modules\SharpDXSceneViewer\Views\SceneView.xaml.cs	50	17	Gemini.Demo
    Error	13	Argument 1: cannot convert from 'SharpDX.Toolkit.Graphics.GraphicsDevice' to 'SharpDX.Toolkit.Graphics.GraphicsDevice [d:\Users\xxx\Desktop\gemini-master\src\packages\SharpDX.2.6.3\Bin\DirectX11-Signed-net40\SharpDX.Toolkit.Graphics.dll]'	D:\Users\xxx\Desktop\gemini-master\src\Gemini.Demo\Modules\SharpDXSceneViewer\Views\SceneView.xaml.cs	50	46	Gemini.Demo
    Error	14	The best overloaded method match for 'SharpDX.Toolkit.Graphics.Texture2D.Load(SharpDX.Toolkit.Graphics.GraphicsDevice, System.IO.Stream, SharpDX.Toolkit.Graphics.TextureFlags, SharpDX.Direct3D11.ResourceUsage)' has some invalid arguments	D:\Users\xxx\Desktop\gemini-master\src\Gemini.Demo\Modules\SharpDXSceneViewer\Views\SceneView.xaml.cs	54	21	Gemini.Demo
    Error	15	Argument 1: cannot convert from 'SharpDX.Toolkit.Graphics.GraphicsDevice' to 'SharpDX.Toolkit.Graphics.GraphicsDevice [d:\Users\xxx\Desktop\gemini-master\src\packages\SharpDX.2.6.3\Bin\DirectX11-Signed-net40\SharpDX.Toolkit.Graphics.dll]'	D:\Users\xxx\Desktop\gemini-master\src\Gemini.Demo\Modules\SharpDXSceneViewer\Views\SceneView.xaml.cs	54	36	Gemini.Demo
    Error	16	Argument 2: cannot convert from 'string' to 'System.IO.Stream'	D:\Users\xxx\Desktop\gemini-master\src\Gemini.Demo\Modules\SharpDXSceneViewer\Views\SceneView.xaml.cs	54	54	Gemini.Demo
    Error	17	'SharpDX.Toolkit.Graphics.GraphicsDevice' does not contain a definition for 'Clear' and no extension method 'Clear' accepting a first argument of type 'SharpDX.Toolkit.Graphics.GraphicsDevice' could be found (are you missing a using directive or an assembly reference?)	D:\Users\xxx\Desktop\gemini-master\src\Gemini.Demo\Modules\SharpDXSceneViewer\Views\SceneView.xaml.cs	67	21	Gemini.Demo
    Error	18	'SharpDX.Toolkit.Graphics.GraphicsDevice' does not contain a definition for 'BackBuffer' and no extension method 'BackBuffer' accepting a first argument of type 'SharpDX.Toolkit.Graphics.GraphicsDevice' could be found (are you missing a using directive or an assembly reference?)	D:\Users\xxx\Desktop\gemini-master\src\Gemini.Demo\Modules\SharpDXSceneViewer\Views\SceneView.xaml.cs	74	37	Gemini.Demo
    Error	19	'SharpDX.Toolkit.Graphics.GraphicsDevice' does not contain a definition for 'BackBuffer' and no extension method 'BackBuffer' accepting a first argument of type 'SharpDX.Toolkit.Graphics.GraphicsDevice' could be found (are you missing a using directive or an assembly reference?)	D:\Users\xxx\Desktop\gemini-master\src\Gemini.Demo\Modules\SharpDXSceneViewer\Views\SceneView.xaml.cs	74	73	Gemini.Demo
    Error	23	The namespace prefix "dd" is not defined.	D:\Users\xxx\Desktop\gemini-master\src\Gemini.Demo\Modules\FilterDesigner\Views\GraphView.xaml	11	5	Gemini.Demo
    Error	24	DesignTimeGraphViewModel is not supported in a Windows Presentation Foundation (WPF) project.	D:\Users\xxx\Desktop\gemini-master\src\Gemini.Demo\Modules\FilterDesigner\Views\GraphView.xaml	11	5	Gemini.Demo
    Error	25	The name "ElementViewModel" does not exist in the namespace "clr-namespace:Gemini.Demo.Modules.FilterDesigner.ViewModels".	D:\Users\xxx\Desktop\gemini-master\src\Gemini.Demo\Modules\FilterDesigner\Views\GraphView.xaml	92	18	Gemini.Demo
    Error	26	The name "ElementViewModel" does not exist in the namespace "clr-namespace:Gemini.Demo.Modules.FilterDesigner.ViewModels".	D:\Users\xxx\Desktop\gemini-master\src\Gemini.Demo\Modules\FilterDesigner\Views\GraphView.xaml	93	18	Gemini.Demo

**Comment by tgjones** [comment]
Ah yes, the documentation hasn't been updated to match the new location of the FilterDesigner demo. (I've just merged most of the samples into a single Gemini.Demo, with a SampleBrowser, which should make finding samples easier.)

Are you sure you're compiling the latest version? Do you have any local changes? That demo application "works on my machine", and also [compiles successfully on AppVeyor](https://ci.appveyor.com/project/tgjones/gemini/branch/master).

**Comment by HellGate94** [comment]
hmm most likely a problem with sharpdx. it seems to use 2.6.3 on my pc (d:\Users\xxx\Desktop\gemini-master\src\packages\SharpDX.2.6.3\...) that does not have the toolkit any more (and your machine and the buildserver have version 2.5.0 cached maybe?)

**Comment by a5rGithub** [comment]
@HellGate94 did you solve this problem? I am experiencing the same build errors. Did you downgrade SharpDX to 2.5 and dit it help?

**Comment by HellGate94** [comment]
@a5rGithub No. I ended up just reading the Graph sample code, since it was the only component i needed and it does not require any SharpDX references

**Comment by a5rGithub** [comment]
after compiling second time most issues were resolved.

**Comment by tgjones** [comment]
This sounds like the usual thing that happens with NuGet and SharpDX. Because the SharpDX NuGet package uses a `.targets` file, you might need to restart Visual Studio after installing the NuGet package, and then try compiling again.

> after compiling second time most issues were resolved.

@a5rGithub "most", or all?

**Comment by a5rGithub** [comment]
@tgjones almost all. XNA framework isn't installed on the machine, so the XNA dependent libs don't compile. But at this moment i wasn't interested in the interaction with XNA so didn't install. cool project by the way :)

**Comment by tgjones** [comment]
Ah, thanks - yes, the XNA dependency is somewhat awkward. I'd like to remove it altogether, but some people might still be using it - I'll probably just put it in its own `.sln`, and remove it from the main `Gemini.sln`. Then everything you need will either be in the `lib` folder, or will be downloaded from NuGet when you build.

**Comment by mwpowellhtx** [comment]
FWIW, I am in the same boat. I would be fine just having a couple of additional configurations in the current solution. HTH

**Comment by HellGate94** [comment]
ok managed to build it as well. Simply went to gemini-master\src\Gemini.Demo\packages.config and chenged the SharpDx version to 2.5.0 before i opened it. Then build => errors => clean => build and it works

**Comment by mwpowellhtx** [comment]
Was that an up- or down-grade? Is there a pull request for it? Thank you...

**Comment by tgjones** [comment]
The reason SharpDX 2.5.0 works first time, I suspect, is because that version of the NuGet package didn't use a `.targets` file. They changed that in 2.6.x (I think; I haven't checked).

But as was mentioned above, compiling a second time should resolve most issues. I don't think there's any problem with Gemini here; just an idiosyncrasy in the way NuGet handles packages with `.targets` files, SharpDX being one example.

**Comment by mwpowellhtx** [comment]
Gemini declares its nuget dependencies, no? i.e. [2.5,] (forgive the notation, its been awhile since I last reviewed the nuget version notation)

**Comment by HellGate94** [comment]
Gemini actually declares version 2.6.3 and thats the problem

**Comment by tgjones** [comment]
But what's the problem? So far I've only seen mentions of issues the first time you try to compile. Compiling a second time should fix it.

I still haven't seen anything that I can fix in Gemini?

**Comment by HellGate94** [comment]
for me it did not build at all with 2.6.3 had to downgrade to 2.5.0 to get it to work. i dont know what he did to make it work but simply changing the demo packages to use 2.5.0 should work fine and avoid the build errors

**Comment by mwpowellhtx** [comment]
It shouldn't take 2+ times to build. That's what we're telling you @tgjones. Even with package restoration turned on, it should take just one time to build, targets or not.

**Comment by tgjones** [comment]
@mwpowellhtx Yes, I think we're talking past each other. I'm saying that it's nothing to do with Gemini. Everyone who uses the SharpDX NuGet package has the same issue. Visual Studio and NuGet don't handle packages with `.targets` files very well. This is a known issue.

[Have a look here](https://github.com/sharpdx/SharpDX/issues/463) for a discussion about this exact issue. Here's what the creator of SharpDX said:

>  It seems that nuget package restore cannot work fine when a nuget package requires a target file to be loaded (as it is the case for SharpDX). So the issue is more with nuget itself.

Note that you only need to do a second build *the first time you compile Gemini on a new machine*. After that, you'll have the packages locally and it will work as you'd expect.

**Comment by mwpowellhtx** [comment]
@tgjones Sorry didn't catch that.

**Comment by HellGate94** [comment]
closing issue
