### ISSUE TITLE
ErrorList - the Messages command always unchecked

### ISSUE THREAD

**Issue by yurgen1981** [tgjones/gemini#128]
There is bug in the Update method:

  void ICommandHandler<ToggleMessagesCommandDefinition>.Update(Command command)
        {
            command.Enabled = MessageItemCount > 0;
            command.Checked = command.Checked && _errorList.ShowMessages;
            command.Text = command.ToolTip = Pluralize("Message", MessageItemCount);
        }

The line
            command.Checked = command.Checked && _errorList.ShowMessages;
must have the following view:
            command.Checked = command.Enabled && _errorList.ShowMessages;

**Comment by tgjones** [comment]
Thanks! Fixed now.
