### ISSUE TITLE
Nuget package is outdated.

### ISSUE THREAD

**Issue by Aminion** [tgjones/gemini#135]
It have 0.5.0 version and it outdated.

**Comment by tgjones** [comment]
Yep, thanks for the reminder. I'll do my best to release 0.6.0 soon - there are still some loose ends that need to be tied up.

**Comment by Airmonos** [comment]
I have some time (and need) to help with this. What can I do?

**Comment by tgjones** [comment]
@Airmonos Thank you! There are two main issues I'd like to resolve before release v0.6:

* #124 - we need to enable localisation for menu items / toolbar buttons
* #137 - it should be easy (ideally one line of code) to remove all default menu items, toolbar buttons, and keyboard shortcuts.

If you fancy having a go at either of those, that would be great! We can discuss further, separately within each issue.

**Comment by tgjones** [comment]
I've implemented #124, and updated the docs. Only #137 now stands between us and v0.6. I'll try to look at it in the next day or two.

**Comment by tgjones** [comment]
v0.6 is now ready to go. I'm just waiting for AppVeyor to fix a big with deploying binaries to GitHub ([bug details here](http://help.appveyor.com/discussions/problems/2971-github-deployment#comment_37911139)). Once that's fixed, I'll deploy the release.

**Comment by tgjones** [comment]
I'm happy to be able to close this one :) New NuGet packages are live, and [I've blogged about v0.6 here](http://timjones.tw/blog/archive/2015/09/20/gemini-v0.6-released).
