### ISSUE TITLE
How to set theme

### ISSUE THREAD

**Issue by BigWinston** [tgjones/gemini#136]
Hi,

How can I configure the theme for a new application I'm creating based on Gemini, just like in the demo applications (VS2013)?  I've searched through the code but can't see how its done.  Can someone please point me in the right direction?  Thanks!

BW

**Comment by tgjones** [comment]
As long as you follow the [Getting started](https://github.com/tgjones/gemini#getting-started) instructions, and use the latest version of the code from here on GitHub, you shouldn't need to do anything special to enable the VS2013 theme. If you want to set the theme to something other than the default, you can do so:

``` csharp
IoC.Get<IThemeManager>().SetCurrentTheme("Blue");
```

The theme can also be set by users through the Settings dialog, which can be accessed through the menus, unless you've explicitly removed that menu option.

**Comment by BigWinston** [comment]
Hi, Thanks.

Ok, I'm using the nuget package.  Will that contain the latest code, or do your recommend I clone it and do it outside of nuget?

**Comment by mwpowellhtx** [comment]
:+1: I'd like to see the Nuget updated as well, since there are some interesting updates in the repo. I've been working from a Git submodule in the meantime.

**Comment by tgjones** [comment]
@BigWinston For now, clone the repo - it contains quite a few changes made since the last NuGet release.

There's a separate issue - #135 - about updating the NuGet package.
