### ISSUE TITLE
ExcludeMenuItemDefinition and CommandKeyGestureService 

### ISSUE THREAD

**Issue by SGStino** [tgjones/gemini#137]
I have tried to replace the open and save menu options by custom implementations because of the way my application works with files. Only "solution/project" types are files, everything else is embedded.

Because of that, editors get launched from a "solution explorer" and not the open file commands.

But to override that, I have to remove the existing commands and add my own ones, this works for the menus, but not for the KeyGuestures as they still get added by the CommandKeyGestureService. So I had to override this service:

```C#
    [Export(typeof(ICommandKeyGestureService))]
    public class CommandKeyGestureService : ICommandKeyGestureService
    {
        private readonly CommandDefinitionBase[] _commandDefinitions;
        private readonly ICommandService _commandService;
        private readonly ExcludeMenuItemDefinition[] _excludedCommandDefinitions;

        [ImportingConstructor]
        public CommandKeyGestureService(
            [ImportMany] CommandDefinitionBase[] commandDefinitions, [ImportMany] ExcludeMenuItemDefinition[] excludedCommandDefinitions,
            ICommandService commandService)
        {
            _commandDefinitions = commandDefinitions;
            _commandService = commandService;
            _excludedCommandDefinitions = excludedCommandDefinitions;
        }

        public void BindKeyGestures(UIElement uiElement)
        {
            var withoutExcludedDefinitions = _commandDefinitions.Where(c => !_excludedCommandDefinitions.Any(e => e.MenuItemDefinitionToExclude.CommandDefinition == c));
            var withGuestures = withoutExcludedDefinitions.Where(k => k.KeyGesture != null);
            foreach (var commandDefinition in withGuestures)
                uiElement.InputBindings.Add(new InputBinding(
                    _commandService.GetTargetableCommand(_commandService.GetCommand(commandDefinition)),
                    commandDefinition.KeyGesture));
        }
    }
```

Now I can easily replace menu items. And i don't think i have affected commands without menu items in this way as i only look at excluded ExcludeMenuItemDefinitions.

But a more out of the box supported version of this would be better i guess. Maybe something along the lines of ExcludeCommandDefinitions or ExcludeKeyGuestureCommandDefinitions.

**Comment by mwpowellhtx** [comment]
I've tried to persuade Tim to adopt a more declarative approach. Not to worry about whether whatever is being included/excluded, but to declare what's what, simple as that. So far, to my knowledge, no movement on that subject.

**Comment by SGStino** [comment]
Ye, default menu is annoying, maybe something on the bootstrapper "IncludeDefaults" if he really wants to push his defaults. But to my application, most of the defaults have to be replaced or hidden anyway.

**Comment by tgjones** [comment]
@SGStino thanks for raising this issue. That is definitely a bug :) I'll have a think about the best way to solve it. Some kind of "clear all defaults" has been asked for by a number of people, so that's probably part of the solution.

I do want to provide defaults though. It's people new to Gemini who need defaults the most, so in order to make it easy to get started, I want it to be opt-out, not opt-in (much the same as Visual Studio Shell).

But point taken about making it easy to opt-out.

**Comment by mwpowellhtx** [comment]
@tgjones to be clear, no need to "clear" anything as long as things are declared. examples, patterns, are perfectly valid, but they should all be declared. life is much simpler that way.

**Comment by tgjones** [comment]
@mwpowellhtx what do you mean? Can you give a code example? The big recent change to commands is exactly that: making it declarative.

**Comment by SGStino** [comment]
Yes, you could declare some defaults and put those lines required for declaration on the github wiki.  Or even put them in a nuget Gemini.Modules.Defaults. Still easy enough. 

You have to dig through the code anyway to do something more advanced than the examples. And then defaults are really getting on your nerves because you can't find how to get rid of them without in depth knowledge of MEF to be honest.

**Comment by mwpowellhtx** [comment]
@SGStino precisely :+1: ... but at this point, entrenchment has set in, IMO. :+1: declarative, default "empty", don't clear anything, just add in the ones you want.

**Comment by SGStino** [comment]
And @tgjones yes, commands is exactly that, but your "MenuDefinitions.cs" files need to go out to have the "default empty", maybe move them to a seperate nuget package? That would make it also easy to have 50% of the defaults  by just copying in those declarations from the sourcecode without having to recompile the gemini assemblies.

**Comment by mwpowellhtx** [comment]
@SGStino :+1: this is a great suggestion.

**Comment by tgjones** [comment]
@SGStino If I was able to reduce it to a single line of code, to remove all defaults, would you still consider that too much?

**Comment by tgjones** [comment]
(Obviously, I'll be updating the docs for the 0.6.0 release, so this will be mentioned in the docs, either way.)

**Comment by SGStino** [comment]
well, the thing with the single line of code is a bit of "yes or no", no? While the separate module, you can always copy in what you need from the source if you would want some defaults but not all?

**Comment by mwpowellhtx** [comment]
it's not so unusual to provide a default (null) edge case (i.e. empty) and a "standard document", sort of thing. does this make sense @tgjones ? subscribers could derive from either as they so chose.

**Comment by tgjones** [comment]
I realise we could go around in circles talking about this indefinitely, but I think this is what I'd like to do:
* Provide defaults
* Provide a single-line-of-code means of removing all defaults

If you want to pick-and-choose, then you have the choice of either:
* Removing all defaults, and then add them back one-by-one, or
* Removing defaults one-by-one

I think that is the best of both worlds:
* For newcomers, you get a nice out-of-box experience.
* For people who want to clear all the defaults and customise menu items, I think we can expect them to read the docs enough to find the one line of code to do so. It's more likely that this group will read the docs, than newcomers.

**Comment by SGStino** [comment]
Also, would it be possible to override an existing CommandHandler? I like the default definition, but the handler that matches it doesn't do what I want it to do. Along with all the changes you suggested above, that would make for ultimate customization with defaults. 

I just think it's a bit much, that's why I suggested the "simpler" approach.

**Comment by tgjones** [comment]
> Also, would it be possible to override an existing CommandHandler?

@SGStino That's supposed to work already - let me know if it doesn't, because that would be a bug. I intended that modules provide default handlers, such as `ExitCommandHandler`, but you should also be able to provide your own for the same command definition, i.e. `ExitCommandDefinition`. In general, when doing MEF lookups, Gemini priorities classes found in non-Gemini assemblies.

**Comment by SGStino** [comment]
the nightly build/prerelease one too?

**Comment by deepakguptamum** [comment]
how to exclude a submenu Item in Gemini (there are options for Menuitem ,MenuItemDefinition and MenuItemGroup)
