### ISSUE TITLE
Gemini.Demo crashes in File New

### ISSUE THREAD

**Issue by matthewclendening** [tgjones/gemini#140]
Doing a File New command will result in a NullReferenceException being flagged in TargetableCommand.cs line 36. The IEditorProvider implementation in the demo handles .txt and .cmd files. If you try and create these as new files, the cause is in the demo's EditorViewModel ApplyOriginalText() method: the _view member is null. If you chose a different extension during the File New, it will be because the _view member in CodeEditorViewModel's ApplyOriginalText() method is null . In both cases the view has yet to be set because the OnViewLoaded override has not be called yet. Doing a null check of the _view member fixes the issue.

**Comment by gmich** [comment]
I've encountered this problem as well.
In `EditorProvider.cs` i changed

        public async Task New(IDocument document, string path)
        {
             await ((CodeEditorViewModel) document).New(path);
        }
To

        public async Task New(IDocument document, string name)
        {
             var doc = (CodeEditorViewModel) document;
             doc.New(name);
        }

Creating the document synchronously fixes the problem, but it's a hacky solution

**Comment by tgjones** [comment]
Well spotted - I'll fix it in the same way as in `OpenFileCommandHandler`.
