### ISSUE TITLE
is there a way to programatically set the active document?

### ISSUE THREAD

**Issue by matthewclendening** [tgjones/gemini#142]
When I call IShell OpenDocument, my File New command fires. Is OpenDocument meant for activating existing docs? Same with _shell.ActiveLayoutItem = someExistingDoc.

**Comment by matthewclendening** [comment]
Insider NewFileCommandHandler, the logic of the Run method ultimately executes when the frameworkelement loaded event fires. But that event is never unhooked - so every time the document (framework element) is made active - I'm  getting the new behavior executing. So I've changed the relevant part of the new command's Run to look like this - which seems to be working better:

	viewAware.ViewAttached += (sender, e) =>
	{
		tag.EditorProvider.New(editor,
				string.Format(Resources.FileNewUntitled, (_newFileCounter++) + tag.FileType.FileExtension));
	};

**Comment by tgjones** [comment]
I get a crash when I change to your suggested code, because `New` ends up calling, for example, `CodeEditorViewModel.ApplyOriginalText`, which expects that `_view` is available.

I think I can instead change it to unhook the `Loaded` event handler once it's been executed the first time.
