### ISSUE TITLE
Clarification re: SharpDX / Helix 3D

### ISSUE THREAD

**Issue by mwpowellhtx** [tgjones/gemini#143]
It's been a little while since I was last following Gemini. Question re: SharpDX. There was discussion of keeping the Helix 3D modules separate from SharpDX, per se. I'd like to see Helix 3D kept separate from the SharpDX modules. I'll go ahead and add that module back in if it's all the same.

**Comment by tgjones** [comment]
Have you looked at the latest code? The modules themselves were always separate, but I've now moved the SharpDX demo back into its own project, as I mentioned in #125.

**Comment by mwpowellhtx** [comment]
Thanks for clarifying.
