### ISSUE TITLE
Backwards compatibility of online Xaml schemas

### ISSUE THREAD

**Issue by mwpowellhtx** [tgjones/gemini#144]
Your schemas have disappeared, or backwards compatibility was broken in the process of upgrading.

```Xaml
xmlns:gemini="http://schemas.timjones.tw/gemini"
```

Suggest keeping version compatibility: i.e.

```Xaml
http://schemas.timjones.tw/gemini/0.5
```

and:

```Xaml
http://schemas.timjones.tw/gemini/0.6
```

**Comment by tgjones** [comment]
Ah, that URL has never existed - it's purely used as a XAML namespace, instead of having to use the slightly-uglier CLR namespace.

**Comment by mwpowellhtx** [comment]
Any workarounds?

**Comment by tgjones** [comment]
What is the bug? I thought you just meant the URL didn't exist, but is Gemini itself breaking in some way?

**Comment by mwpowellhtx** [comment]
It may be more Xna-related. Not everyone has/needs Xna installed. Seems like we've circled that wagon before.

```
Error	48	The tag 'DrawingSurface' does not exist in XML namespace 'http://schemas.timjones.tw/gemini'. Line 10 Position 4.	D:\Source\Spikes\Gemini\gemini\src\Gemini.Demo.Xna\Modules\SceneViewer\Views\SceneView.xaml	10	4	Gemini.Demo.Xna
```

If I just build ``Gemini.Demo``, it seems "okay".

**Comment by tgjones** [comment]
You'll need XNA installed if you want to build the XNA demo, as I mention in the readme. If you don't have XNA installed, just uncheck "Build" next to the XNA projects in Solution Configuration.

**Comment by mwpowellhtx** [comment]
Great thanks.
