### ISSUE TITLE
Inspector views are singleton instead of transient

### ISSUE THREAD

**Issue by mwpowellhtx** [tgjones/gemini#150]
The InspectorView. I've 'successfully' installed an InspectorView in a side-by-side split view in a document window. That's what I want to do with that. But it seems that this view supersedes that of the Inspector Tool Window. When I close the document window, then the view in the tool window operates as 'expected'. What I think should happen is that there should be transient instead of singleton usage of the view when it is installed at user discretion.

**Comment by tgjones** [comment]
It "should" work. Can you provide a sample project with a minimal repro?

**Comment by EchterAgo** [comment]
I think this is related to #148

**Comment by tgjones** [comment]
Thanks @EchterAgo. I don't plan to have multiple inspector tools supported by the built-in `IInspector` - but as mentioned in #148, it's possible to roll your own `IInspector`, but still use the built-in view models and views.
