### ISSUE TITLE
Update to AvalonDock 2.6

### ISSUE THREAD

**Issue by nicolas-garcia** [tgjones/gemini#152]
Hi !

Finally, the version 2.6 of AvalonDock is out ! (http://wpftoolkit.codeplex.com/workitem/20833)

I've tried to update gemini by myself to this version, I've built Xceed.Wpf.AvalonDock.Themes.VS2013 using this new version, but I now have a problem with some missing resources
ResourceKey='SemiTransparentWhiteBrush'
ResourceKey='TransparentWhiteBrush'

Have you any idea where I can found them ?

Here a screenshot of the current result 
![capture](https://cloud.githubusercontent.com/assets/1201859/12228686/4fd30f44-b83f-11e5-8739-7e9049fe1514.PNG)

Thank you :)

**Comment by tgjones** [comment]
Thanks for the heads-up! I'm glad to see that bug has been fixed at last. I have updated both Xceed.Wpf.AvalonDock.Themes.VS2013 (at least, my fork of it) and Gemini to Extended.Wpf.Toolkit v2.6. I didn't get the problem you mentioned, with missing resources - I'm not sure why...
