### ISSUE TITLE
Rebuild error with Gemini.Modules.CodeCompiler

### ISSUE THREAD

**Issue by FOstyn** [tgjones/gemini#153]
Just tried to rebuild the whole solution and the project 'Gemini.Modules.CodeCompiler' returns the following error: 
Metadata file '..\packages\Microsoft.CodeAnalysis.Analyzers.1.0.0\analyzers\dotnet\cs\Microsoft.CodeAnalysis.Analyzers.dll' could not be found
--> there is still a reference to version 1.0.0, the packages folder has already v1.1.0.

**Comment by tgjones** [comment]
Thanks! This error only happens in VS2015, but I've been using VS2013. Fixed now.
