### ISSUE TITLE
NullReferenceException in EditorBase if there is no ActiveItem

### ISSUE THREAD

**Issue by KingKnecht** [tgjones/gemini#157]
Hi,
I want to modify an item, but I don't have an ActiveItem at this point.
For better understanding what's going on I have uploaded a video:

[Demo video](https://www.youtube.com/watch?v=B4_R6DyvNV8&feature=youtu.be)

What could I do, if I want to edit items which are not part of an document. Same situation would be e.g. if you rename a file in the SolutionExplorer in VS.
Mayne my "SheetTree" should be a document? Would it be possible to move it to the left side as it is right now?

Thx,
Sven

**Comment by KingKnecht** [comment]
Ok, made my sheet inheriting from "Document" and activate it when it's clicked in the sheet tree. Now I'm able to edit the name of a sheet. But that also means that the sheet/document must be active/open. Any chance to modify the name of document without opening it?

Thx,
Sven

**Comment by EchterAgo** [comment]
This problem is caused by EditorBase using undo/redo by default. Pull request #188 added a toggle to EditorBase to enable/disable undo. Maybe the undo/redo in EditorBase should only be used if there is an active document?

**Comment by EchterAgo** [comment]
I think #202 should fix this.
