### ISSUE TITLE
ShellView BusyIndicator

### ISSUE THREAD

**Issue by ejaaron** [tgjones/gemini#163]
It would be great if WPF Toolkit BusyIndicator could be integrated into ShellView.

**Comment by ryanvs** [comment]
I've found the BusyIndicator to be more useful in my documents, rather than the shell. You could also make a custom ShellView/ShellViewModel though.

**Comment by Kibnet** [comment]
Indeed, I am also using WPF Toolkit BusyIndicator. It connects easily and used anywhere as you like. I believe that the task can be closed.
