### ISSUE TITLE
Unable to run basic app

### ISSUE THREAD

**Issue by cameronws** [tgjones/gemini#164]
I used v0.5 of this project a while ago without issues. I'm now facing issues with the current version (0.62).

I've installed the GeminiWPF NuGet package into a WPF4.5 project - had to install Caliburn.Micro.Core then Caliburn.Micro modules first, removed the MainWindow.xaml and changed the App.xaml to reflect the same reference and Resources as demo'd in the readme. Building the solution completes sucessfully, yet running the solution returns an error:

> The invocation of the constructor on type 'Gemini.AppBootstrapper' that matches the specified binding constraints threw an exception.
> Could not load type 'Caliburn.Micro.AssemblySource' from assembly 'Caliburn.Micro.Platform, Version=3.0.1.0, Culture=neutral, PublicKeyToken=8e5891231f2ed21f'. 

I've tried compiling a zipped version of this project yet I am unable to find all the dependent projects/dll's - mainly the AvalonDock theme references.

Can someone please guide me in the right direction to get this app running.

**Comment by cameronws** [comment]
Problem is with my version of NuGet Package Manager.

**Comment by K2** [comment]
how'd you fix it? I have same error right now...

**Comment by AndrewRublyov** [comment]
Yeah, same here

**Comment by Kelsinga** [comment]
If you find a fix for this error, please post the solution.
