### ISSUE TITLE
Command shortcut text looks bad if the command text is long enough

### ISSUE THREAD

**Issue by yusuf-gunaydin** [tgjones/gemini#184]
If the command name is longer than `MinWidth="90"` of its column definition, the shortcut key text will be shown adjacent to it. This can be fixed by adding left margin to the shortcut text block.

Gemini\Themes\VS2013\Controls\Menu.xaml:

    
    ...
    <TextBlock x:Name="InputGestureText" Grid.Column="2" 
                           Padding="0 2 2 2"
						   Margin="6 0 0 0"
                           VerticalAlignment="Center"
                           Text="{TemplateBinding InputGestureText}" 
                           DockPanel.Dock="Right" />

**Comment by EchterAgo** [comment]
Should be fixed by pull request #198

**Comment by tgjones** [comment]
Fixed by #198.
