### ISSUE TITLE
Multi language support

### ISSUE THREAD

**Issue by JobaDiniz** [tgjones/gemini#220]
How to translate menus/toolbar?

**Comment by Kibnet** [comment]
@JobaDiniz, Try to translate resources by [ResX Manager](https://visualstudiogallery.msdn.microsoft.com/3b64e04c-e8de-4b97-8358-06c73a97cc68).

**Comment by Kibnet** [comment]
See how translation of standard modules. Proceed by analogy. As a result, you should create a .resx resource files for each language. In your module, you must replace the string suitable for translation into calling resource manager with a matching key.

**Comment by oldrev** [comment]
@Kibnet Thanks. I will dig into it.

**Comment by tgjones** [comment]
Closing - thanks for the help @Kibnet. @oldrev, if you have any specific problem specific to Gemini when translating your module, please feel free to open a new issue.
