### ISSUE TITLE
Wiki Creation

### ISSUE THREAD

**Issue by RobertBColton** [tgjones/gemini#222]
Hi there! I stumbled upon your really awesome project and have been playing around with it. I noticed something about the repository that I did not particularly like, and that is the excessively long read me file. I notice that I can already create a Wiki for the repo even though I have not pushed any code. I would be willing to dedicate my time to moving all of the information to separate wiki pages to make it easier to navigate. I do not want to just up and do this so I felt I should discuss here it first.

**Comment by Kibnet** [comment]
Great idea! I'm in.

**Comment by RobertBColton** [comment]
Well I guess since creating it won't hurt anything I will go ahead and get started. Then if @tgjones decides he don't like it that way he can delete it.

**Comment by RobertBColton** [comment]
So that turned out a lot easier than I expected, I guess GitHub wiki's can parse markdown.

I've converted the entire readme over to a Wiki now. I did not leave everything the same so that I could organize it a little better. For example, since Documents and Persisted Documents were short sections, I made them a single page on the new Wiki.

https://github.com/tgjones/gemini/wiki

I hope everyone likes this and finds it useful. I was having a hard time myself reading everything before.

**Comment by ryanvs** [comment]
Personally, I like the long readme file. Too many projects have sparse readme files and this project really shows you some of its capabilities and gives you screenshots.

Also, did you see the documentation at http://documentup.com/tgjones/gemini that is essentially the same as the readme?

**Comment by RobertBColton** [comment]
@ryanvs, really what would make the Wiki unnecessary is if GitHub simply added a navigation bar for the readme file that would work like it does on a Wiki. Then you could jump around quickly and the long README would not make a difference. I think a GitHub feature request is in order.

**Comment by ryanvs** [comment]
@RobertBColton I agree it would be really nice to have a navigation bar for markdown files. The documentup site has that functionality though, so it didn't bother me too much at the time.

**Comment by jasonnator** [comment]
Take a look at mkdocs then. Super simple and easily customizable.

**Comment by jasonnator** [comment]
http://www.mkdocs.org

**Comment by jasonnator** [comment]
If you guys need help, I could add a pull request with the functionality later this weekend.

**Comment by tgjones** [comment]
Closing for now, because I think http://documentup.com/tgjones/gemini, combined with the wiki (thanks @RobertBColton) is good enough for now. If anyone disagrees, please feel free to open a new issue.
