### ISSUE TITLE
Verify Caliburn.Micro 3.0.1 compatiblity

### ISSUE THREAD

**Issue by antonfirsov** [tgjones/gemini#236]
If I update Caliburn.Micro to newest Caliburn.Micro 3.0.1 package, it breaks Gemini for me. I have the following exception:
`"The composition produced a single composition error. The root cause is provided below. Review the CompositionException.Errors property for more detailed information.\r\n\r\n1) Could not load type 'Caliburn.Micro.ExtensionMethods' from assembly 'Caliburn.Micro.Platform, Version=3.0.1.0, Culture=neutral, PublicKeyToken=8e5891231f2ed21f'.\r\n\r\nResulting in: An exception occurred while calling the 'OnImportsSatisfied' method on type 'Gemini.Modules.MainWindow.ViewModels.MainWindowViewModel'.\r\n\r\nResulting in: Cannot activate part 'Gemini.Modules.MainWindow.ViewModels.MainWindowViewModel'.\r\nElement: Gemini.Modules.MainWindow.ViewModels.MainWindowViewModel -->  Gemini.Modules.MainWindow.ViewModels.MainWindowViewModel -->  AssemblyCatalog (Assembly=\"Gemini, Version=0.6.2.0, Culture=neutral, PublicKeyToken=null\")\r\n"`

**Comment by tgjones** [comment]
Closing for now, because it's not an issue with the current version of Gemini - but I'd accept a PR that updates Caliburn.Micro to the latest version.

**Comment by antonfirsov** [comment]
I did some investigation, and the cause of the issue was that Gemini tried to load stuff from assemblies "Gu.Localization" and "Gu.Wpf.Localization", and could not find them, because "Gu" packages are not listed as explicit dependencies.

AFAIK, there is no constraint in Gemini, which prevents users from updating to Caliburn 3.0, so I think it's still an open issue.

If you can provide some info about how "Gu.Localization" is used, I can give a try to make a PR. Gemini is a great project, I'd be really happy if I could help keeping it up to date.

**Comment by antonfirsov** [comment]
Haven't noticed when made my previous comment, but PR #243 seems to solve this.

**Comment by tgjones** [comment]
Ah yes, so it does - thanks.
