### ISSUE TITLE
How to Show (Login) Window before MainWindow display

### ISSUE THREAD

**Issue by tcsnhj** [tgjones/gemini#24]
Hi, Tgjones:

Our group want to make a program looks like "Photoshop" with some 3d render functions. So we find Gemini is our best choice.

But when I try to show a (Login) window, or config window before MainWindow start, I met some difficulty. I found the IWindow interface, and what to do something, but all my attempts failed over the past 12 hours!

I konw it's a simple function, but maybe I gone the wrong way. Could you please help me? Thanks a lot.

**Comment by KingKnecht** [comment]
Hi,

if I use the code shown above, I get a "Index out of range exception" in "ThemeManager.SetCurrentTheme".

Any ideas?

Thx.
