### ISSUE TITLE
ICommandHandler Update is not called after a Run command

### ISSUE THREAD

**Issue by ppedro74** [tgjones/gemini#247]
I have the following code:

      
```
async Task ICommandHandler<DevicesConnectCommandDefinition>.Run(Command command)
{
	//Step 1
	this.DeviceState = DeviceState.Busy;

	await Task.Run(() =>
	{
		//Run some slow code, release the UI
	});

	this.DeviceState = DeviceState.Connect;
	
	//Step 4
}

void ICommandHandler<DevicesDisconnectCommandDefinition>.Update(Command command)
{
	//Step 2 Command is disabled
	command.Enabled = this.DeviceState == DeviceState.Disconnect;
}

void ICommandHandler<DevicesDisconnectCommandDefinition>.Update(Command command)
{
	//Step 3 Command is disabled
	command.Enabled = this.DeviceState == DeviceState.Connected;
}

```
when i press a toolbar button the Run command is executed, i start a task to run a slow operation, the UI is released and step2, step3 (Update) methods are immediately executed ONE single time each other. No more updates.

The tasks finishes, the run commands ends and still no Updates

if a press somewhere on the toolbar, or the active window, the Update methods are called.

What i'm doing wrong ? 

Thanks for reading.

**Comment by tgjones** [comment]
Gemin relies on WPF's CommandManager.RequerySuggested event to trigger calling its Update methods. This event is raised at somewhat indeterminate points in time, although it's usually after mouse or keyboard input.

You can manually force this to be called with CommandManager.InvalidateRequerySuggested:
https://msdn.microsoft.com/en-us/library/system.windows.input.commandmanager.invalidaterequerysuggested(v=vs.110).aspx

Hope that helps. Feel free to re-open if not.

**Comment by wallencis** [comment]
If someone is wondering about this issue, you have to execute CommandManager.InvalidateRequerySuggested() on the main thread like this:
`Application.Current.Dispatcher.Invoke(new System.Action(() =>
            {
                CommandManager.InvalidateRequerySuggested();
            }));`
