### ISSUE TITLE
Error when docking

### ISSUE THREAD

**Issue by agrper0** [tgjones/gemini#25]
Sometimes the docking fails. I have recreated the error in the sample Project.

Just start the sample Project (make sure that the file ApplicationState.bin is deleted) and then take the Inspector tool pane and drop it on the lower or upper part of the compass in the middle. The whole document pane disappears and nothing but application shutdown works. Attached is an image that decribes where to drop the pane. If you start the application again the pane is located at the bottom but with no height. To recreate the issue you need to delete ApplicationState.bin.
![gemini-dock](https://f.cloud.github.com/assets/5344965/1985409/bf28b070-843d-11e3-8b06-b0467402c36a.png)

**Comment by Camuvingian** [comment]
Hi Tim, any news on this one?

**Comment by tgjones** [comment]
@Camuvingian Only that the AvalonDock bug is apparently fixed in 1.6. But thanks to the odd release schedule for Extended WPF Toolkit, that version won't be released to non-commercial customers until 1.7 or 1.8 has been released to commercial customers. See my comments in the work item, linked above, for my opinion on that :)

**Comment by mwpowellhtx** [comment]
+1 to the best Extended WPF Toolkit weirdness. Once upon a time I took a hard look at them and figured they had one too many issues lagging yo make it worthwhile. I thought you were using CaliburnMicro? Or does CM use ExWPFTk?

**Comment by tgjones** [comment]
@mwpowellhtx When Xceed acquired AvalonDock, they merged it (well, included it) with their existing Extended WPF Toolkit. So AvalonDock releases are now tied to the Extended WPF Toolkit release schedule.

**Comment by mwpowellhtx** [comment]
@tgjones yes I understand that.
