### ISSUE TITLE
'System.ArgumentException':  'value' parameter cannot be NaN.

### ISSUE THREAD

**Issue by raizam** [tgjones/gemini#252]
Hi,

First of all this is a great project, congrats for all your work.

Using the demo, I get an exception that seems internal to WPF, in WindowsBase.dll.

To reproduce it in the demo:
1. Open the toolbox panel
2. Click "Auto Hide" on it
3. Click on the toolbox tab, and resize it

**Comment by nestquik** [comment]
The same thing for me.

**Comment by diluculo** [comment]
Please see [this](https://github.com/4ux-nbIx/AvalonDock.Themes.VS2013/pull/14) and #233. Thank Kibnet.

No error with the latest AvalonDock.Themes.VS2013.

**Comment by nestquik** [comment]
We totally need add it as NuGet Package.
