### ISSUE TITLE
Problems when upgrading to the latest NUGET packages

### ISSUE THREAD

**Issue by pstollery** [tgjones/gemini#258]
Hi,

I've updated the monogame and sharpdx packages and this breaks gemini. Anyone looking into bringing it up to date?

**Comment by tgjones** [comment]
In what way(s) does it break Gemini? Build errors?

**Comment by pstollery** [comment]
Runtime errors around SharpDX - because it has moved lots of methods to SharpDX.Mathemetics.

**Comment by tgjones** [comment]
Closing this because it's not an issue with Gemini, more a potential issue when upgrading dependencies. But if someone wants to contribute a PR with updated NuGet packages for Gemini's dependencies, that would be great.
