### ISSUE TITLE
Need to learn the source code of "Merlin Editor"

### ISSUE THREAD

**Issue by githubnihao** [tgjones/gemini#26]
Hi ,I download the source code of Gemini .But in the source code ,I can not find the source code of the  "Merlin Editor" . I want to design a 3dmax like IDE using Gemini,the  "Merlin Editor" is very similar to my aim. Can you  provide the  "Merlin Editor" source code? Or provide the download Url? My Gmail is dahanihao@gmail.com .Thanks  a  lot.

**Comment by bencrossman** [comment]
I'd love to get some code like that too. Doesnt have to be everything but just the Scene Hierarchy / Inspector and the Scene view with transform gizmos would be awesome. Looking to creating a similar MonoGame level editor. Thanks
