### ISSUE TITLE
messenger between modules

### ISSUE THREAD

**Issue by maxmont** [tgjones/gemini#261]
Hello,

I'm discovering this IDE framework for my new application.
I'm designing new modules and it's working like a charm.
But I need to send notifications from modules and receive these message in other modules.
I don't know Caliburn (just MVVM light). I see Eventaggregator.
Do I have to use EventAggregator for that. If yes, I know see exactly how. If not, does it exist an existing mechanism in the framework?

Thanks in advance for your help

**Comment by tgjones** [comment]
You don't have to use `IEventAggregator` - but yes, that's probably what I'd use.

Gemini already adds it to the app bootstrapper, so you don't need to worry about that bit.

[This Caliburn Micro documentation page](https://github.com/Caliburn-Micro/caliburn-micro.github.io/blob/master/documentation/event-aggregator.md) has a lot of details about how to use Caliburn's event aggregator.
