### ISSUE TITLE
Status update

### ISSUE THREAD

**Issue by damien122** [tgjones/gemini#265]
Hi,

do you have a status update about this project? 
The last release was on 20 Sep 2015 ... what is nearly 2 years ago.
Can someone tell the planed future of this project?

I need this information for a decision in my company project.

**Comment by tgjones** [comment]
> do you have a status update about this project?

I'm no longer actively working on the project. However, I do accept pull requests, as long as they are high quality, inline with my vision for the project, and don't take me too long to review.

> Can someone tell the planed future of this project?

There currently isn't one. If another contributor steps up and wants to take over maintenance, I would be open to that, but in the meantime, it is what it is: feel free to use if it's useful to you, or not if not.
