### ISSUE TITLE
How to customize the Gemini ide

### ISSUE THREAD

**Issue by githubnihao** [tgjones/gemini#27]
Hi

I download the Gemini sourcecode. Run it in such enviroment:Win7,Visual studio 2012.

I want to customize the ide UI. So I did like this:

To customize Gemini.Demo.FilterDesigner UI,I go to the Gemini.Modules.Inspector source code , and find the Module.cs file,Open the c# source code,I fine the code like this:

public override void Initialize()
{
MainMenu.All.First(x => x.Name == "View")
.Add(new MenuItem("Inspector", OpenInspector));
}

I note the source code,then the code like this:

public override void Initialize()
{
//MainMenu.All.First(x => x.Name == "View")
//.Add(new MenuItem("Inspector", OpenInspector));
}

Then run the solution ,and set the Gemini.Demo.FilterDesigner as the StartOne project.When it runs, I find in Main menu ,in the View menu ,the "Inspector" disapeared. It is just I want to have.

But when the program runs ,I find the "Inspector"tool box is aready loaded and settled to the right of the windows,I want the "Inspector" tool box will not loaded when the program runs ,How can I customize the source code?

Needs help ,thanks a lot.

**Comment by kudilovich** [comment]
The questioner above modified Gemini. Modules code. I guess this is not ideal. Could you please clarify how menuitems can be modified from Module definition. It is clear how to add new menuitems. Is it possible to remove menuitems as well?
