### ISSUE TITLE
Gemini ToolBox Filtering and Sorting

### ISSUE THREAD

**Issue by deepakguptamum** [tgjones/gemini#280]
Hi ,

There is no feature of searching in ToolBox to quickly find the toolitems

Also there is no way for sorting the ToolBox Items (like which group item to show on top and sort it accordingly)

Can you please incorporate or let me know how to do it?

Thank you!!

**Comment by luferau** [comment]
deepakguptamum,
See method

private void RefreshToolboxItems(IShell shell)

in gemini\src\Gemini\Modules\Toolbox\ViewModels\ToolboxViewModel.cs

where BindableCollection<ToolboxItemViewModel> _items is being filled.

**Comment by deepakguptamum** [comment]
Hi,

Problem is with the toolbox groups, I want some specific group at the top
and arrange others accordingly.

Using the refresh method it will only refresh the toolbox but not arrange
the toolbox items.

If there is search facility in toolbox then it would also do the need,
otherwise I need to arrange group

Can you please let me know the way

Thank you

Regards
Deepak

**Comment by luferau** [comment]
Deepak,
as one of the solutions you can add new property to ToolboxItemAttribute attribute, ToolboxItem and ToolboxItemViewModel classes. For example 

int SortRank {get;set;}

After that you can sort your BindableCollection<ToolboxItemViewModel> _items; in different ways. In ViewModel code or in XAML.
Please, see this examples 

https://stackoverflow.com/questions/19112922/sort-observablecollectionstring-c-sharp
https://stackoverflow.com/questions/5803786/sorting-observablecollection

**Comment by deepakguptamum** [comment]
If there is any possibility of adding a textbox like it is there in Property Grids in the toolbox so that i can search the particular elements

**Comment by sblkr** [comment]
I added a search  in 5921a975e5900759ccdad0d287ceb1585d1e7e42 and requested pull #286

**Comment by deepakguptamum** [comment]
I am using nuget so how to include this changes of filtering toolbox

**Comment by sblkr** [comment]
this wont work with nuget. you have to wait for a new nuget release, if that change will be approved, or download the source and change it there manually.

**Comment by deepakguptamum** [comment]
Ohh ok let me know. When the nuget is available or if replacing dll or any other solution would work for this or I can override toolboxmodel

**Comment by deepakguptamum** [comment]
I tried with changing the code and building the Gemini DLL and removing the reference and adding reference of Gemini DLL Build ,but it gives a lot of errors when loading at runtime ,so please let me know any alternative way where i can use this functionality

**Comment by sblkr** [comment]
That's because the master branch in this repo is miles ahead of the nuget version. You need to rebuild all of your used modules with the updated gemini version.
Clone this Repo or my [fork](https://github.com/sblkr/gemini) where the update is already in. Open the soulution file with Visual Studio and build the whole project. Maybe delete unnecessary modules. For Reference either add those projects to your solution and reference via build dependencies or via "Add Reference" in your project tree.

**Comment by deepakguptamum** [comment]
Thank you for the answers ,I have build the Gemini DLL and added Gu Localization DLL and also replaced Mahapps.Metro DLL and maded specific version property to false and finally made it working.
