### ISSUE TITLE
How to save state of ViewModel(GraphViewModel)

### ISSUE THREAD

**Issue by deepakguptamum** [tgjones/gemini#283]
Can you please let me know how to save state of elements and connections in graph view model and load it back ?

Thank you!

**Comment by luferau** [comment]
You need to inherit your GraphViewModel class from PersistedDocument and override DoLoad and DoSave methods.

For example my DoSave method:

`        protected override Task DoSave(string filePath)
        {
            if (string.IsNullOrEmpty(filePath))
            {
                filePath = AppDomain.CurrentDomain.BaseDirectory + DisplayName;
            }
            var proj = new SerializableProject();
            proj.SetData(Elements, Connections);
            
             // Here you can serialize proj object (XML, JSON etc.)

            return TaskUtility.Completed;
        }
`

SerializableProject class has two properties for serializing:

`
        public List<ElementViewModel> Elements { get; set; }
        public List<SerializableConnection> SerializableConnections { get; set; }
`

Elements are serialized directly. For serialization connection i use temporary class SerializableConnection

`    public class SerializableConnection
    {
        public int ElementFromIndex { get; set; }
        public int ConnectorFromIndex { get; set; }
        public int ElementToIndex { get; set; }
        public int ConnectorToIndex { get; set; }
    }
`
And SerializableProject  SetData method

`
public void SetData(List<ElementViewModel> elements, List<ConnectionViewModel> connections)
        {
            Elements = elements;
            // Create SerializableConnections List from original ConnectionViewModel List
            foreach (var connection in connections)
            {
                var serializableConnection = new SerializableConnection
                {
                    ElementFromIndex = Elements.IndexOf(connection.From.Element),
                    ConnectorFromIndex = connection.From.Element.OutputConnectors.IndexOf(connection.From),
                    ElementToIndex = Elements.IndexOf(connection.To.Element),
                    ConnectorToIndex = connection.To.Element.InputConnectors.IndexOf(connection.To)
                };
                SerializableConnections.Add(serializableConnection);
            }
        }
`
Also in SeriazableProject there is possibility to convert Connection back:

`       
public List<ConnectionViewModel> Connections
        {
            get
            {
                // Create ConnectionViewModel List from SerializableConnections List
                var connectionList = new List<ConnectionViewModel>();
                foreach (var serializableConnection in SerializableConnections)
                {
                    try
                    {
                        var connection = new ConnectionViewModel(
                        Elements[serializableConnection.ElementFromIndex].OutputConnectors[serializableConnection.ConnectorFromIndex],
                        Elements[serializableConnection.ElementToIndex].InputConnectors[serializableConnection.ConnectorToIndex])
                        {
                            FromPosition = Elements[serializableConnection.ElementFromIndex].OutputConnectors[serializableConnection.ConnectorFromIndex].Position,
                            ToPosition = Elements[serializableConnection.ElementToIndex].InputConnectors[serializableConnection.ConnectorToIndex].Position
                        };
                        connectionList.Add(connection);
                    }
                    catch (Exception ex)
                    {
                        MessageBox.Show(ex.Message, "Load model file error!");
                    }
                }
                return connectionList;
            }
        }
`

And finally DoLoad method in GraphView model:

protected override Task DoLoad(string filePath)
        {
            // Here you load (deserialize) your SerializableProject proj object from XML, JSON  etc. file

            // Add Elements
            Elements.AddRange(proj.Elements);
            
            // Add Connections
            Connections.AddRange(proj.Connections);

            return TaskUtility.Completed;
        }

**Comment by deepakguptamum** [comment]
OutputConnectors is not present anywhere ,is it correct ? or instead of OutputConnectors there is something else that needs to be used

**Comment by deepakguptamum** [comment]
Also SerializableConnections.Add(serializableConnection); this line gives me null reference error because  SerializableConnections is null and

**Comment by luferau** [comment]
> OutputConnectors is not  present anywhere ,is it correct ?

This is because I added to ElementViewModel ability to have multiple output connectors. I apologize for not having indicated this.

**Comment by luferau** [comment]
> Also SerializableConnections.Add(serializableConnection); this line gives me null reference error because SerializableConnections is null and

it's not guaranteed work code, it's just an answer to the question " how to save state of elements and connections in graph view model and load it back"

**Comment by deepakguptamum** [comment]
ok let me try with some alternative ,if you find it please let me know

**Comment by deepakguptamum** [comment]
I have written custom code and took a different approach for achieving this

**Comment by Levi555** [comment]
@deepakguptamum Hi.Can you explain the method? thank you!
