### ISSUE TITLE
AvalonDock Update to Version 3.5. is available

### ISSUE THREAD

**Issue by Dirkster99** [tgjones/gemini#297]
I have updated the Open Source version from AvalonDock to stabilize issues like the items mentioned here:
https://github.com/tgjones/gemini/issues/281

and added a dark theme to the mix:
https://github.com/Dirkster99/AvalonDock

...just wondering if this could be interesting for Gemini as well. I tried using [Dirkster.AvalonDock.Themes.VS2013](https://www.nuget.org/packages/Dirkster.AvalonDock.Themes.VS2013) instead of the version 2.9. nuget package - can get it to compile but cannot get it to run since the BootStrapper thows an exception - not sure why(?) but pretty sure this is probably not a stopper...

**Comment by JobaDiniz** [comment]
I wonder how did you update... it seems like there is no free version of AvalonDock anymore. The latest version is 3.7 and it requires a license key.

**Comment by Dirkster99** [comment]
Can you describe your problem in more detail please? I just downloaded the current version 3.4 from [xceeds](https://github.com/xceedsoftware/wpftoolkit) repository and it builds fine for me. This was the base of my updated version that is documented in [my own repository](https://github.com/Dirkster99/AvalonDock).

Its been a while since I attempted an update of AvalonDock in Gemini but I think I might just removed the available references (to a static AvalonDock V2.9 project?) and replaced it with the Nugets from my own repository [Dirkster99/AvalonDock](https://github.com/Dirkster99/AvalonDock).

The result was a compiling version that would crash on start-up which I could not resolve at the time since I do not know Gemini that well :-( are you interested in trying to get an update to work? I wonder if the [issue you entered here](https://github.com/xceedsoftware/wpftoolkit/issues/1423) is not already fixed in my repository (I would not be surprissed)?

**Comment by Dirkster99** [comment]
Just in case someone is actuall reading this: [Version 3.5 (with 15 known issues + 4 new issues fixed) of AvalonDock](https://github.com/Dirkster99/AvalonDock) was just released

**Comment by Dirkster99** [comment]
Looks like has been fixed in the meantime - closing issue.
