### ISSUE TITLE
Tool window content disappears when it is not pinned. 

### ISSUE THREAD

**Issue by VirtualMagic** [tgjones/gemini#312]
Tool window content disappears when it is no longer pinned. Only the full class name is displayed. As soon as the window is pinned the content appears again. What am I doing wrong?

Screenshot Links:
[Pinned window](https://files.sms-online.net/Handlers/AnonymousDownload.ashx?file=0f7acc75&links=true)
[Unpinned window](https://files.sms-online.net/Handlers/AnonymousDownload.ashx?file=16f532e1&links=true)

**Comment by OldNo7** [comment]
I had the same issue. I changed Xceed.Wpf.AvalonDock.dll to the one from Dirkster99  https://github.com/Dirkster99/AvalonDock
I'm using version 3.6.2 from nuget package Dirkster.AvalonDock

**Comment by kornman00** [comment]
In theory, PR #334 (merged yesterday) fixes this? It uses Dirkster99's fork.
