### ISSUE TITLE
nuget最新程序包安装报错

### ISSUE THREAD

**Issue by yeungroot** [tgjones/gemini#329]

**Comment by tgjones** [comment]
What package installation error are you seeing?

**Comment by JustF2A** [comment]
0.7版本，.net framework 4.6.1 报错
1.0.37版本，.net framework 4.61 没问题

**Comment by JustF2A** [comment]
0.7版本，.net framework 4.6.1  报错
1.0.37版本，.net framework 4.61 没问题
