### ISSUE TITLE
Avalonia Version

### ISSUE THREAD

**Issue by furesoft** [tgjones/gemini#330]
A Avalonia Port would be really awesome for cross platform IDEs

**Comment by MikiraSora** [comment]
This is a large project and all dependent projects/projects need to support Avalonia, such as Caliburn Micro and AvalonDock. CM has already started planning to support Avalonia, but AvaloniaDock needs to be replaced with other Docking implementations that can support Avalonia.

Not only that, there are also many break changes in the code migration of user projects
