### ISSUE TITLE
How to compare ThemeManager.CurrentTheme.Name

### ISSUE THREAD

**Issue by diluculo** [tgjones/gemini#336]
In my project, I'd like to do something when the theme is changed. For this, I did a simple comparison of `CurrentTheme.Name`. But, the problem is that it is not "Dark" but "어둡게"(dark in Korean) when Korean is selected. Please give me a hint how to know which theme is selected.

My code is:
````C#
_themeManager.CurrentThemeChanged += OnThemeChanged;

private void OnThemeChanged(object sender, EventArgs e)
{
   var themeManager = sender as ThemeManager;
   if (themeManager == null) return;

   if (themeManager.CurrentTheme.Name == "Dark")
   { ... }
   else if (themeManager.CurrentTheme.Name == "Blue")
   { ... }
   else
   { ... }
}
````

**Comment by EchterAgo** [comment]
You can use `themeManager.CurrentTheme is DarkTheme` or check `themeManager.CurrentTheme.GetType().Name == "DarkTheme"`.

**Comment by diluculo** [comment]
@EchterAgo Thanks a million. Both are working.
