### ISSUE TITLE
 Begging for open Merlin Editor's source code

### ISSUE THREAD

**Issue by githubnihao** [tgjones/gemini#46]
Unit project urgent need to do a simple version of 3dsmax.Originally intended to be developed based gemini, but we have little foundation, the process being blocked.Merlin Editor is very similar to our aims, so We  Begging for open Merlin Editor's source code,We are very eager to learn the experience of the project.
Begging  beggin .....Thanks Thanks......

**Comment by bencrossman** [comment]
I'd love to get some code like that too. Doesnt have to be everything but just the Scene Hierarchy / Inspector and the Scene view with transform gizmos would be awesome. Looking to creating a simple MonoGame level editor. Thanks
