### ISSUE TITLE
Build error following along in the Demo

### ISSUE THREAD

**Issue by mwpowellhtx** [tgjones/gemini#84]
Errors after updating to latest CM and Xceed Toolkit:

```
Error   1   The name "AppBootstrapper" does not exist in the namespace "http://schemas.timjones.tw/gemini". I:\Source\Kingdom Software\Football\Simulator\Football.Arena.Editor.Wpf\App.xaml    9   21  Football.Arena.Editor.Wpf
Error   3   A value of type 'AppBootstrapper' cannot be added to a collection or dictionary of type 'ResourceDictionary'.   I:\Source\Kingdom Software\Football\Simulator\Football.Arena.Editor.Wpf\App.xaml    9   21  Football.Arena.Editor.Wpf
Error   5   Unknown build error, 'Could not load type 'Caliburn.Micro.Bootstrapper`1' from assembly 'Caliburn.Micro, Version=2.0.1.0, Culture=neutral, PublicKeyToken=8e5891231f2ed21f'. Line 9 Position 22.'   I:\Source\Kingdom Software\Football\Simulator\Football.Arena.Editor.Wpf\App.xaml    9   22  Football.Arena.Editor.Wpf
```

I am making an effort to follow along the demo in my own project.

I'm not sure what happened. There's a corresponding update to Gemini that needs to happen to keep up with it? I am running Gemini v0.5, versus the latest CM and Xceed.

**Comment by kudilovich** [comment]
Great framework! The NuGet version 0.5 still gives the following error when loading bootstrapper:
`3	Unknown build error, 'Could not load type 'Caliburn.Micro.Bootstrapper '1' from assembly 'Caliburn.Micro, Version=2.0.1.0, Culture=neutral, PublicKeyToken=8e5891231f2ed21f'. `
Any plans to update the NuGet package?

**Comment by tgjones** [comment]
@kudilovich Thanks!

Gemini v0.5 was built against Caliburn.Micro v1.5.2 - if you reference that version, it should work correctly.

Yes - I do plan to release Gemini v0.6 soon. I've been delayed by other things, but it's definitely in the pipeline.

**Comment by kudilovich** [comment]
Thanks for your reply. I can't seem to figure out one thing though (not related to NuGet version anymore). If I make a solution by modifying Gemini.Demo project even a more recent Caliburn.Micro version works fine. However if I start a new solution and insert Gemini via "Add existing projects" and then try to replicate module and view classes (similar to the demo project) I get the bootstrapper exception. Are there any requirements for the bootstrapper to work correctly, that I might have missed?

**Comment by tgjones** [comment]
Have a look at the docs [here](http://documentup.com/tgjones/gemini#getting-started). You'll need to add some stuff to your `App.xaml`. It sounds like that's the error you're getting (if so, that's a different bootstrapper exception to the one you mentioned above).

**Comment by kudilovich** [comment]
Thanks a lot. I did have the required stuff in App.xaml
Looks like namespaces were off in the app.config
This solved the problem.
